language: node_js
sudo: false
branches:
  only:
  - gh-pages
env:
  global:
  - URL=""
  - DECISION="https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"
script:
- echo "ok"
after_success:
- FILES=`git diff-tree --no-commit-id --name-only -r ${TRAVIS_COMMIT}`
- NAME=$(./get_spec_name.sh $FILES)
- if [[ $NAME=="custom" ]]; then URL="http://w3c.github.io/webcomponents/spec/custom/W3CTRMANIFEST"; secure: "dVxt8F2BIMbfcwX6Kn3H11H6/F55NI1IkzL38IQpH0G+zg3EbBLOC737QT0kHzM0p875FoVAFH2X6Ro1NWmkk+KRskIhS3+MCwWWfoxZZwKnZ5qZVMZPwzBej2vASGCwKC8aZwblZfw0vrq960b8SCxiK59zCWsPeRZJq0pCRMc="; fi
- if [[ $NAME=="shadow" ]]; then URL="http://w3c.github.io/webcomponents/spec/custom/W3CTRMANIFEST"; secure: "dVxt8F2BIMbfcwX6Kn3H11H6/F55NI1IkzL38IQpH0G+zg3EbBLOC737QT0kHzM0p875FoVAFH2X6Ro1NWmkk+KRskIhS3+MCwWWfoxZZwKnZ5qZVMZPwzBej2vASGCwKC8aZwblZfw0vrq960b8SCxiK59zCWsPeRZJq0pCRMc="; fi
- if [[ $NAME=="imports" ]]; then URL="http://w3c.github.io/webcomponents/spec/imports/W3CTRMANIFEST";secure: "N6O+a5bWF1qBKhd1I9rc/nKodegZF9rxdeY3d+7M+kaWj+AphrxQr/kDaKb8h6CYVQjQIcibRMfMPEwGhkUQlh9A/ohvu2ZsVk0e0VmoN556knc1vvlqhE7y5iFYOQvaXq0596n6qfdJ/7Vbpio9cmN+f/5DlujqMKYYbNq/Rtw="; fi
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION"
  --data "token=$TOKEN"'