language: node_js
sudo: false
branches:
  only:
  - gh-pages
env:
  global:
  - URL=""
  - DECISION="https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"
install:
- FILES=`git diff-tree --no-commit-id --name-only -r ${TRAVIS_COMMIT}`
- for item in $FILES; do if [[ "$item" == "spec/"* ]]; then if [[ "$item" == "spec/imports"* ]]; then URL="http://w3c.github.io/webcomponents/spec/imports/W3CTRMANIFEST" TOKEN="N6O+a5bWF1qBKhd1I9rc/nKodegZF9rxdeY3d+7M+kaWj+AphrxQr/kDaKb8h6CYVQjQIcibRMfMPEwGhkUQlh9A/ohvu2ZsVk0e0VmoN556knc1vvlqhE7y5iFYOQvaXq0596n6qfdJ/7Vbpio9cmN+f/5DlujqMKYYbNq/Rtw="; fi if [[ "$item" == "spec/custom"* ]]; then URL="http://w3c.github.io/webcomponents/spec/custom/W3CTRMANIFEST" TOKEN="dVxt8F2BIMbfcwX6Kn3H11H6/F55NI1IkzL38IQpH0G+zg3EbBLOC737QT0kHzM0p875FoVAFH2X6Ro1NWmkk+KRskIhS3+MCwWWfoxZZwKnZ5qZVMZPwzBej2vASGCwKC8aZwblZfw0vrq960b8SCxiK59zCWsPeRZJq0pCRMc="; fi if [[ "$item" == "spec/shadow"* ]]; then URL="http://w3c.github.io/webcomponents/spec/shadow/W3CTRMANIFEST" TOKEN="CLabndVgc4h9ITqFv2tvGPmb3s2RASJAzZLTZcgmbjZed63rH0Hv09tnbU7ymiBz6l5jhRPdBLYc3SsOK3GBBO1EfAWmwRbfMk70BxSQL94CZnCQm3HKYK7nBu2kLP6I5AIoJew2/kRPSxa1EmakW/DbXGnPjwivHRisH43Yj00="; fi fi; done
- secure: "$TOKEN"
script:
- echo "ok"
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION"
  --data "token=$TOKEN"'